### ISSUE TITLE
Spectral analysis method

### ISSUE THREAD

**Issue by linareyne** [DisMAL-audio-team/DisMAL#3]
We've talked a bit about the shortcomings of FFT-based analysis in the facebook group.  We should discuss potential alternatives to implement, what features we need to extract from analyses of audio samples, how different options will affect peak/partial detection, etc.

**Comment by nkahrs** [comment]
I was pointing out issues with FFTs not to imply that there's anything better out there, but just to show that the results aren't as Platonic as Sethares seems to think they are. As long as we're not making any excessively grandiose claims about a spectrum being exact, FFTs are fine.
